services:
  postgres:
    image: postgres:15-alpine
    container_name: cheque04_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: receipts_db
    ports:
      - "5432:5432"
    volumes:
      - cheque04_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d receipts_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api-server
    container_name: cheque04_api
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./etc:/srv/etc
      - ./api/swagger:/app/api/swagger
    environment:
      - SWAGGER_DIR=/app/api/swagger

  swagger:
    image: swaggerapi/swagger-ui
    container_name: cheque04_swagger
    volumes:
      - ./etc/swagger-ui-config/swagger-initializer.js:/usr/share/nginx/html/swagger-initializer.js:ro
    ports:
      - "8081:8080"
    depends_on:
      - api

  import:
    build:
      context: ./import
    container_name: cheque04_import
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./etc/config.yml:/etc/config.yml
      - ./var/data:/var/data
    command: ["/usr/local/bin/import"]
    profiles: ["import"]

  db_tools_scheme:
    build:
      context: ./tools/db
      dockerfile: Dockerfile.scheme
    container_name: cheque04_db_tools_scheme
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./etc/config.yml:/etc/config.yml
    command: ["/usr/local/bin/scheme"]
    profiles: ["db_tools_scheme"]

  db_tools_cleanup:
    build:
      context: ./tools/db
      dockerfile: Dockerfile.cleanup
    container_name: cheque04_db_tools_cleanup
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./etc/config.yml:/etc/config.yml
    command: ["/usr/local/bin/cleanup"]
    profiles: ["db_tools_cleanup"]

  frontend:
    build:
      context: ./frontend
    container_name: cheque04_frontend
    ports:
      - "5173:5173"
      - "5001:5001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080/api/v1
    depends_on:
      - api

volumes:
  cheque04_postgres_data: