services:
  postgres:
    image: postgres:15-alpine
    container_name: cheque_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cheque_db
    ports:
      - "5432:5432"
    volumes:
      - cheque_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cheque_db"]
      interval: 5s
      timeout: 5s
      retries: 5

#  server:
#    build:
#      context: .
#      dockerfile: server/Dockerfile
#    container_name: cheque_server
#    ports:
#      - "8080:8080"
#      - "50051:50051"
#    depends_on:
#      postgres:
#        condition: service_healthy
#    volumes:
#      - ./etc:/srv/etc
#      - ./api/gen/swagger:/app/api/gen/swagger
#      - ./var/upload:/var/upload
#    environment:
#      - SWAGGER_DIR=/app/api/gen/swagger

  import:
    build:
      context: .
      dockerfile: import/Dockerfile
    container_name: cheque_import
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./etc/config.yml:/etc/config.yml
      - ./var/data:/var/data
    command: ["/usr/local/bin/app"]
    profiles: ["import"]

  db_tools_scheme:
    build:
      context: .
      dockerfile: tools/db/Dockerfile.scheme
    container_name: cheque_db_tools_scheme
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./etc/config.yml:/etc/config.yml
    command: ["/usr/local/bin/app"]
    profiles: ["db_tools_scheme"]

  db_tools_cleanup:
    build:
      context: .
      dockerfile: tools/db/Dockerfile.cleanup
    container_name: cheque_db_tools_cleanup
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./etc/config.yml:/etc/config.yml
    command: ["/usr/local/bin/app"]
    profiles: ["db_tools_cleanup"]

  swagger:
    image: swaggerapi/swagger-ui
    container_name: cheque_swagger
    volumes:
      - ./etc/swagger-ui-config/swagger-initializer.js:/usr/share/nginx/html/swagger-initializer.js:ro
    ports:
      - "8081:8080"
#    depends_on:
#      - server

volumes:
  cheque_postgres_data: