services:
  postgres:
    image: postgres:15-alpine
    container_name: cheque04_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: receipts_db
    ports:
      - "5432:5432"
    volumes:
      - cheque04_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d receipts_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api-server
    container_name: cheque04_api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./etc:/srv/etc

volumes:
  cheque04_postgres_data: