// Code generated by template. DO NOT EDIT.
package receiptss

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"

	pb "github.com/meesooqa/cheque/api/gen/pb/receiptpb/v1"
	"github.com/meesooqa/cheque/api/services"
	"github.com/meesooqa/cheque/db/db_types"
	"github.com/meesooqa/cheque/db/models"
	"github.com/meesooqa/cheque/db/repositories"
)

type DbModel = models.Receipt

type ServiceServer struct {
	*services.BaseService[DbModel, pb.Model, pb.GetListRequest]
	pb.UnimplementedModelServiceServer
}

func NewServiceServer(dbProvider db_types.DBProvider) *ServiceServer {
	base := services.NewBaseService[DbModel, pb.Model, pb.GetListRequest](
		repositories.NewReceiptRepository(dbProvider),
		NewConverter(),
		NewFilterProvider(),
	)
	return &ServiceServer{BaseService: base}
}

func (o *ServiceServer) Register(grpcServer *grpc.Server) {
	pb.RegisterModelServiceServer(grpcServer, o)
}

func (o *ServiceServer) RegisterFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) error {
	return pb.RegisterModelServiceHandlerFromEndpoint(ctx, mux, endpoint, opts)
}
