system:
  data_path: "test/data"
  upload_path: "test/upload"
server:
  port: 4321
grpc_server:
  endpoint: "localhost:11111"
db:
  host: "localhost"
  port: 1234
  sslmode: "disable"
  user: "admin"
  password: "adminpw"
  dbname: "app_db"
gorm_gen_proto:
  path_maps: "data/maps"
  path_tmpl: "data/templates"
  proto_root: "../common/proto"
  protoc_root: "../api/pb"
  services_root: "../api/services"
