FROM golang:1.23-alpine AS build
COPY . /build
WORKDIR /build
RUN go get -u . && go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o /build/scheme -ldflags "-s -w" /build/cmd/scheme/main.go

FROM alpine:latest
COPY --from=build /build/scheme /usr/local/bin/scheme
CMD ["/usr/local/bin/scheme"]
